<a href="https://colab.research.google.com/github/minseo-k3/esaa/blob/main/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [22]:
print(np.__version__)
np.show_config()

2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
a=np.zeros(10, dtype='int32')
print(a)

[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [10]:
a2=np.array([1,2,3,4,5,6,7,8])
print(a2)
print(a2.nbytes)

[1 2 3 4 5 6 7 8]
64


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
a=np.zeros(10, dtype='int32')
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
a3=np.arange(start=10, stop=50)
print(a3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
a3=np.arange(start=10, stop=50)
a4=a3[::-1]
print(a4)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
a5=np.arange(9)
a5=a5.reshape(3,3)
print(a5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
a6=np.array([1,2,0,0,4,0])
print(np.nonzero(a6))

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [21]:
a7=np.identity(3, dtype='int32')
print(a7)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [20]:
a8=np.random.random((3,3,3))
print(a8)

[[[0.48646651 0.58274419 0.99918055]
  [0.55332175 0.27148526 0.85806367]
  [0.00142751 0.54210379 0.93093046]]

 [[0.94306158 0.90970629 0.71402916]
  [0.84806556 0.38667391 0.50202449]
  [0.25585771 0.26030931 0.96372743]]

 [[0.40764365 0.22037425 0.26099394]
  [0.70621593 0.5903705  0.9518191 ]
  [0.16972436 0.39231184 0.90782782]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [24]:
a9=np.random.random((10,10))
print(a9)
print(a9.min(), a9.max())

[[3.64334275e-01 9.73556555e-01 5.61563895e-01 6.40713411e-01
  7.35662626e-02 8.74181582e-01 2.43792777e-01 2.85014620e-01
  8.00986680e-01 5.33841149e-01]
 [1.12498583e-01 6.46197783e-01 1.67318587e-01 2.19238117e-01
  5.92949472e-01 3.34655453e-01 4.67332969e-01 2.29286401e-01
  6.65928910e-01 9.69536722e-01]
 [7.35366094e-01 5.92005756e-01 5.98327364e-01 9.62722976e-01
  6.98574041e-01 6.35595779e-01 7.77731395e-01 7.53111285e-01
  1.73949649e-01 5.49199362e-01]
 [8.55661102e-01 4.81199876e-01 8.31587759e-01 7.96189544e-01
  7.63417300e-01 6.43188798e-01 5.57154172e-01 4.23055758e-01
  4.44866889e-01 1.58696613e-01]
 [5.25517109e-01 2.14590735e-01 6.23865176e-01 8.37797734e-02
  3.31087461e-01 4.17501884e-01 5.78718435e-01 5.53007099e-01
  6.06537116e-01 9.45667530e-01]
 [9.63719092e-01 3.74807870e-01 3.57261492e-01 6.10360649e-01
  6.98055386e-01 7.33134189e-01 1.27536829e-01 1.26573554e-01
  5.68836827e-01 8.15938537e-01]
 [3.45647192e-01 8.88969665e-01 8.79430613e-01 8.18427434e

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [28]:
a10=np.random.random(30)
print(a10.mean())

0.42713646267203226


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [30]:
b=np.ones((4,4), dtype='int32')
b[1:3, 1:3]=0
print(b)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
True
False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [38]:
b2=np.diag([1,2,3,4], k=-1)
print(b2)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [13]:
c= np.zeros((10, 10), dtype='int32')
c[1::2, ::2] = 1
c[::2, 1::2]=1
print(c)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [14]:
print(np.unravel_index(99, (6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [17]:
c2=np.random.random((5,5))
c2=(c2-c2.mean()) / c2.std()
print(c2)

[[-0.88365782 -1.6764274   0.81700795 -0.23547577 -1.61927752]
 [-0.46006258  0.45953514 -1.37065116  1.40535637  0.03360868]
 [ 0.51042204  1.41392877  0.86184512  0.11120899 -0.52700805]
 [-0.98941543 -0.12176944  1.41027308 -0.93099018 -0.10292657]
 [-0.71610194  0.39410408  1.72206713 -0.9523008   1.44670733]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [21]:
color = np.dtype([('R', np.ubyte),('G', np.ubyte), ('B', np.ubyte),('A', np.ubyte)
])

print(color)


[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]
