<a href="https://colab.research.google.com/github/minseo-k3/ESAA_YB/blob/main/YB_0904_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np
a=np.random.random((5,3))
b=np.random.random((3,2))

print(np.dot(a,b))

[[1.03487692 0.97266345]
 [0.60854517 0.60158892]
 [0.87376603 0.99350561]
 [0.88202195 0.91009682]
 [0.90751016 1.05161539]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [39]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[(a>=3) & (a<=8)]*=-1
print(a)


[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9
10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z<Z>Z 가 성립하지 않음


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan

0

nan을 정수로변환 후 다시 실수로 변환하여 실수값 나옴

In [19]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_1003/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_1003/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_1003/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [21]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

In [22]:
common=np.intersect1d(Z1,Z2)

print(common)

[1 2 4 5 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

좌변은 실수 영역에서만 계산이 되기 때문에 none이 나오지만, 우변은 복소수 영역까지 확장해서 답이 나오기 때문에 허수가 나온다. 따라서 두 값은 다르다.-> False

False. nan!=1j


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
import numpy as np
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A=np.random.random(5)
B=np.random.random(5)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
print(A)

[-0.06406938 -0.03844196 -0.11541433 -0.10417015 -0.06583478]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
A=np.random.uniform(0,10,10)
A1 = (A - A % 1).astype(int)
A2 = (A // 1).astype(int)
print(A1)
print(A2)

[2 0 2 4 7 5 7 4 6 4]
[2 0 2 4 7 5 7 4 6 4]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
z = np.zeros((5,5)) + np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
z = np.random.random(10)
z.sort()
print(z)

[0.03410002 0.14655105 0.29408229 0.31920248 0.37420992 0.37442978
 0.41350835 0.4285485  0.75572352 0.80842518]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [24]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [25]:
Z = np.random.random((10, 2))

x = Z[:, 0]
y = Z[:, 1]

r = np.sqrt(x**2 + y**2)
a = np.arctan2(y, x)

polar = np.column_stack((r,a))

print(polar)


[[0.25788554 0.44256042]
 [1.177662   0.80204733]
 [0.79894685 0.31514798]
 [1.21283088 0.74124393]
 [0.59152259 0.6998125 ]
 [0.94473947 1.02392733]
 [1.15171787 0.53613408]
 [0.87914033 0.35021307]
 [0.89817372 0.1444918 ]
 [0.23810131 0.52158058]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [40]:
a=np.random.random(6)

a[a.argmax()]=0

print(a)

[0.14691554 0.54979796 0.         0.19876658 0.42946819 0.24346654]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [44]:
Z = np.arange(100)
v = np.random.uniform(0,100)

a=np.abs(Z - v).argmin()
print(Z[a])


63


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [46]:
Z = np.arange(9).reshape(3,3)

for index, v in np.ndenumerate(Z):
  print(index, v)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [55]:
n=10
p=4
Z=np.zeros((n,n))

np.put(Z, np.random.choice(range(n*n), p, replace = False),5)
print(Z)


[[0. 0. 0. 0. 0. 0. 5. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [53]:
Z = np.random.randint(0, 10, (3, 3))



z1=Z[Z[:,2].argsort()]
print(z1)

[[4 9 2]
 [9 0 7]
 [1 5 9]]
